### ISSUE TITLE
Error feeding query to dataprovider

### ISSUE THREAD

**Issue by mcki0127** [majiameng/yii2-solr#1]
I get this error when I try to feed the query to a dataprovider:

```
Solr ActiveQuery Cancellation function :count
```

```
$query = GroupSolrCollection::find();
$dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => ['pageSize'=>10],
            'sort' => false,
        ]);
```

I'm not quite sure what to do with it.

**Comment by majiameng** [comment]
This component only supports select queries and does not support count. If you want to count, please use \yii::$app->solr to option

**Comment by majiameng** [comment]
> I get this error when I try to feed the query to a dataprovider:
> 
> ```
> Solr ActiveQuery Cancellation function :count
> ```
> 
> ```
> $query = GroupSolrCollection::find();
> $dataProvider = new ActiveDataProvider([
>             'query' => $query,
>             'pagination' => ['pageSize'=>10],
>             'sort' => false,
>         ]);
> ```
> 
> I'm not quite sure what to do with it.


This component only supports select queries and does not support count. If you want to count, please use \yii::$app->solr to option
